service: bob-sls-python-hello

frameworkVersion: '3'

provider:
  name: aws
  region:  eu-central-1  
  runtime: python3.8

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: post 
          cors: true

