service: bob-sls-nodejs-hello

frameworkVersion: '3'

provider:
  name: aws
  region:  eu-central-1    
  runtime: nodejs14.x

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: post 
          cors: true
