service: bob-greencab-trips-summary-ts

frameworkVersion: "3"

provider:
  stage: dev
  name: aws
  region: eu-central-1
  runtime: nodejs14.x

  apiGateway:
    apiKeys:
      - bob-greencab-ts-api-key-${opt:stage, self:provider.stage}  

  environment:
    GREENCAB_TRIPS_SUMMARY_DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.GREENCAB_TRIPS_SUMMARY_DYNAMODB_TABLE}"

functions:
  createGreenCabSummaryTrip:
    handler: greencab/create.create
    events:
      - http:
          path: greencab/trips/summary
          method: post
          private: true
          cors: true

  getGreenCabSummaryTrips:
    handler: greencab/list.list
    events:
      - http:
          path: greencab/trips/summary
          method: get
          cors: true

  getGreenCabSummaryTrip:
    handler: greencab/get.get
    events:
      - http:
          path: greencab/trips/summary/{id}
          method: get
          private: true
          cors: true

  updateGreenCabSummaryTrips:
    handler: greencab/update.update
    events:
      - http:
          path: greencab/trips/summary/{id}
          method: put
          private: true
          cors: true

  deleteGreenCabSummaryTrips:
    handler: greencab/delete.delete
    events:
      - http:
          path: greencab/trips/summary/{id}
          method: delete
          private: true
          cors: true

resources:
  Resources:
    GreenCabTripsSummeryTable:
      Type: AWS::DynamoDB::Table
      # Keeps around the DynamoDB resource when we redeploy/destroy
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.GREENCAB_TRIPS_SUMMARY_DYNAMODB_TABLE}